# This file was generated by GoReleaser. DO NOT EDIT.
cask "muxcp" do
  name "muxcp"
  desc "MCP server multiplexer — aggregate multiple MCP servers behind a single endpoint"
  homepage "https://github.com/moray95/muxcp"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "muxcp"

  on_macos do
    on_intel do
      url "https://github.com/moray95/muxcp/releases/download/v#{version}/muxcp_#{version}_darwin_amd64.tar.gz"
      sha256 "553b82364b4e7b572648bd9c6dd4d45ba9300d85a30ee08028316ccf64146c13"
    end
    on_arm do
      url "https://github.com/moray95/muxcp/releases/download/v#{version}/muxcp_#{version}_darwin_arm64.tar.gz"
      sha256 "c299da90e6444fa1c4bdb979e58801a46642c3a1bf769b4da6ced5bf75b6b0c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/moray95/muxcp/releases/download/v#{version}/muxcp_#{version}_linux_amd64.tar.gz"
      sha256 "3ae2f9e09dae6f02233d7e17562ce484c0f01a0a2fac3503473f10e5d13b88cb"
    end
    on_arm do
      url "https://github.com/moray95/muxcp/releases/download/v#{version}/muxcp_#{version}_linux_arm64.tar.gz"
      sha256 "b64eea46797534ccad8f1977073cef633a8acded76f60581fde2cc9b837d5f50"
    end
  end

  # No zap stanza required
end
