# This file was generated by GoReleaser. DO NOT EDIT.
cask "muxcp" do
  name "muxcp"
  desc "MCP server multiplexer — aggregate multiple MCP servers behind a single endpoint"
  homepage "https://github.com/moray95/muxcp"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "muxcp"

  on_macos do
    on_intel do
      url "https://github.com/moray95/muxcp/releases/download/v#{version}/muxcp_#{version}_darwin_amd64.tar.gz"
      sha256 "d53ab30682b96d995483a8429799210c145594f021f0f7621892938a8f272c28"
    end
    on_arm do
      url "https://github.com/moray95/muxcp/releases/download/v#{version}/muxcp_#{version}_darwin_arm64.tar.gz"
      sha256 "7cd25dc6395655011bb06d534189764ad20bebebebc6947a140776610a9f5a5f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/moray95/muxcp/releases/download/v#{version}/muxcp_#{version}_linux_amd64.tar.gz"
      sha256 "a0a2d6ac04faf1a02f8ad62376d540d9664e3043073786b3ecae8a181687ca90"
    end
    on_arm do
      url "https://github.com/moray95/muxcp/releases/download/v#{version}/muxcp_#{version}_linux_arm64.tar.gz"
      sha256 "d2d4e5dcfcbace48ad907888c2b9681306aedffbdc122f2f56bad56c69c16cd1"
    end
  end

  # No zap stanza required
end
